### ISSUE TITLE
Question about your IndeedBot

### ISSUE THREAD

**Issue by ELIT3E** [programmersRuleTheWorld/indeedBot#1]
hey robbie,

I'm just trying out your bot a bit and I like it a lot. However, I have two problems that I haven't been able to solve for hours.

The bot should work for the German Indeed is it that simple or are there several adjustments that need to be made apart from replacing the URL?

I also got an error from Puppeteer with the following code:

/Users/juliusharpstedt/indeedBot/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:72
                void this.terminate(new Errors_js_1.TimeoutError(`Waiting failed: ${options.timeout}ms exceeded`));
                                    ^

TimeoutError: Waiting for selector `a[data-testid=pagination-page-next]` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (/Users/juliusharpstedt/indeedBot/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:72:37)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

I use the script on my Mac.

Could you maybe give me a tip?

Thanks very much!

Greetings

Julius
![Bildschirmfoto 2023-06-20 um 20 28 54](https://github.com/programmersRuleTheWorld/indeedBot/assets/137210873/79fd065c-24db-4334-ac62-03d9958007d0)

**Comment by programmersRuleTheWorld** [comment]
Hey Julius, thanks for your question.
The bot is working correctly, but I need to add a way for it to exit gracefully when no more options for going to the next page exist.
I will add that in tonight and you should get a notification when it closes this issue.
If the bot is going through the pages and not doing applications though, that just means that that page does not have any "Easily apply" listings on it.
I've found a lot of the easy apply listings are on the first few sets of pages and they get more and more sparse the further into the results the bot gets.

**Comment by programmersRuleTheWorld** [comment]
Hey Julius, I solved the issue of it not exiting gracefully when there are no more pages to find; however, in regards to it working on a different language Indeed - there are some statements that rely on keyword selection to find buttons.
I would recommend perhaps forking the repo to make those changes so you can have a version of it specifically for Indeed in German.
